sonar.organization=git-opusone
sonar.projectKey=Git-Opusone_goprimo-cicd-demo
sonar.projectName=GoPrimo CI/CD Demo

sonar.sources=src
sonar.tests=tests
sonar.exclusions=node_modules/**,coverage/**,ci-lab/**,.github/**

sonar.javascript.lcov.reportPaths=coverage/lcov.info
